import { StyleSheet } from "react-native";

export const colors = {
  background: "#FAF5EB",
  card: "#FCFCF5",
  foreground: "#2C2C2C",
  muted: "#666050",
  border: "#E2D7C3",
  secondary: "#E4DBC5",
  primary: "#3F6B51",
  danger: "#E32626",
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  container: { paddingHorizontal: 18, paddingBottom: 120, gap: 10 },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  title: { fontSize: 24, fontWeight: "800", color: colors.foreground },
  subtitle: { fontSize: 13, color: colors.muted, marginTop: 2 },
  headerIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    alignItems: "center",
    justifyContent: "center",
  },

  profileCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { fontSize: 16, fontWeight: "800", color: "#FFFFFF" },
  profileInfo: { flex: 1, gap: 2 },
  profileName: { fontSize: 16, fontWeight: "700", color: colors.foreground },
  profileEmail: { fontSize: 13, color: colors.muted },

  card: {
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    gap: 12,
  },
  simpleCard: {
    minHeight: 52,
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  sectionTitleRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  sectionLabel: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.5,
    color: colors.muted,
  },
  headerMetaRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  sectionMeta: { fontSize: 13, color: colors.muted },

  emptyDownloads: { paddingVertical: 6 },
  emptyText: { fontSize: 13, color: colors.muted },
  downloadList: { marginTop: 2 },
  downloadRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
  },
  downloadRowDivider: { borderBottomWidth: 1, borderBottomColor: colors.border },
  downloadThumb: { width: 56, height: 56, borderRadius: 8, flexShrink: 0 },
  thumbPlaceholder: { backgroundColor: colors.secondary, alignItems: "center", justifyContent: "center" },
  thumbText: { fontSize: 16, fontWeight: "800", color: colors.muted },
  downloadInfo: { flex: 1, minWidth: 0, gap: 2 },
  downloadTitle: { fontSize: 14, lineHeight: 19, fontWeight: "600", color: colors.foreground },
  downloadMeta: { fontSize: 12, color: colors.muted },
  downloadActions: { flexDirection: "row", alignItems: "center", gap: 6 },
  rowIconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  deleteButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  addDownloadsRow: { flexDirection: "row", alignItems: "center", gap: 10, paddingTop: 2 },
  addDownloadsText: { fontSize: 14, fontWeight: "600", color: colors.primary },

  preferenceRow: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  preferenceText: { flex: 1, gap: 2 },
  preferenceTitle: { fontSize: 14, fontWeight: "600", color: colors.foreground },
  preferenceSubtitle: { fontSize: 12, color: colors.muted },
  divider: { height: 1, backgroundColor: colors.border },

  storageRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  storageTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.secondary,
    overflow: "hidden",
  },
  storageFill: { height: 6, borderRadius: 3, backgroundColor: colors.primary },
  storageText: { fontSize: 12, color: colors.muted, minWidth: 110 },
  simpleText: { fontSize: 14, color: colors.foreground, fontWeight: "500" },

  signOutButton: {
    minHeight: 48,
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  signOutText: { fontSize: 14, color: colors.danger, fontWeight: "700" },
});
