-- Baseline of the `auth` schema, owned by auth-server (Better-Auth).
--
-- Written idempotently (IF NOT EXISTS / guarded enum, FK, and column adds) so it
-- is a no-op against dev/prod databases that already have most of these objects
-- (created by go-api's old migration), while still bootstrapping a fresh
-- database. Future auth schema changes are generated by `bun run db:generate`
-- and need not be idempotent — they only run once.
--
-- Two objects are NEW vs. the pre-existing go-api schema and so are added
-- explicitly for existing databases: the `passkey` table (created below) and
-- `jwks.expires_at` (the ADD COLUMN guard near the end, since CREATE TABLE
-- IF NOT EXISTS skips the already-existing jwks table).
CREATE SCHEMA IF NOT EXISTS "auth";
--> statement-breakpoint
DO $$ BEGIN
	CREATE TYPE "auth"."user_role" AS ENUM('user', 'admin');
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "auth"."account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "auth"."jwks" (
	"id" text PRIMARY KEY NOT NULL,
	"public_key" text NOT NULL,
	"private_key" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "auth"."passkey" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"public_key" text NOT NULL,
	"user_id" text NOT NULL,
	"credential_id" text NOT NULL,
	"counter" integer NOT NULL,
	"device_type" text NOT NULL,
	"backed_up" boolean NOT NULL,
	"transports" text,
	"created_at" timestamp,
	"aaguid" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "auth"."session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	"impersonated_by" text,
	CONSTRAINT "session_token_key" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "auth"."user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"role" "auth"."user_role" DEFAULT 'user' NOT NULL,
	"banned" boolean DEFAULT false,
	"ban_reason" text,
	"ban_expires" timestamp,
	"image" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_email_key" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "auth"."verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- jwks already exists on databases migrated by go-api; add the 1.6 column there.
ALTER TABLE "auth"."jwks" ADD COLUMN IF NOT EXISTS "expires_at" timestamp;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "auth"."account" ADD CONSTRAINT "account_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "auth"."passkey" ADD CONSTRAINT "passkey_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "auth"."session" ADD CONSTRAINT "session_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "auth"."session" ADD CONSTRAINT "session_impersonated_by_fkey" FOREIGN KEY ("impersonated_by") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_auth_account_provider_account" ON "auth"."account" USING btree ("provider_id" text_ops,"account_id" text_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_auth_account_user_id" ON "auth"."account" USING btree ("user_id" text_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_auth_passkey_user_id" ON "auth"."passkey" USING btree ("user_id" text_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_auth_passkey_credential_id" ON "auth"."passkey" USING btree ("credential_id" text_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_auth_session_expires_at" ON "auth"."session" USING btree ("expires_at" timestamp_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_auth_session_token" ON "auth"."session" USING btree ("token" text_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_auth_session_user_id" ON "auth"."session" USING btree ("user_id" text_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_auth_user_banned" ON "auth"."user" USING btree ("banned" bool_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_auth_user_email" ON "auth"."user" USING btree ("email" text_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_auth_user_role" ON "auth"."user" USING btree ("role" enum_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_auth_verification_identifier" ON "auth"."verification" USING btree ("identifier" text_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_auth_verification_value" ON "auth"."verification" USING btree ("value" text_ops);
