services:
  postgres:
    build:
      context: ./docker/db
      args:
        PG_VERSION: 17
        PG_SEARCH_VERSION: 0.20.5
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5432:5432'
