/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedGraphRouteImport } from './routes/_authenticated/graph'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedSuggestionsIndexRouteImport } from './routes/_authenticated/suggestions/index'
import { Route as AuthenticatedNotesIndexRouteImport } from './routes/_authenticated/notes/index'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedNotesIdRouteImport } from './routes/_authenticated/notes/$id'
import { Route as AuthenticatedLibraryCollectionsIndexRouteImport } from './routes/_authenticated/library/collections/index'
import { Route as AuthenticatedLibraryItemIdIndexRouteImport } from './routes/_authenticated/library/$itemId/index'
import { Route as AuthenticatedDiscoverPodcastsIndexRouteImport } from './routes/_authenticated/discover/podcasts/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedLibraryCollectionsCollectionIdRouteImport } from './routes/_authenticated/library/collections/$collectionId'
import { Route as AuthenticatedLibraryItemIdTranscriptRouteImport } from './routes/_authenticated/library/$itemId/transcript'
import { Route as AuthenticatedLibraryItemIdReflectRouteImport } from './routes/_authenticated/library/$itemId/reflect'
import { Route as AuthenticatedLibraryItemIdHighlightsRouteImport } from './routes/_authenticated/library/$itemId/highlights'
import { Route as AuthenticatedDiscoverPodcastsSlugRouteImport } from './routes/_authenticated/discover/podcasts/$slug'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users/$id'
import { Route as AuthenticatedLibraryItemIdTakeawaysIndexRouteImport } from './routes/_authenticated/library/$itemId/takeaways/index'
import { Route as AuthenticatedLibraryItemIdNotesIndexRouteImport } from './routes/_authenticated/library/$itemId/notes/index'
import { Route as AuthenticatedLibraryItemIdTakeawaysNewRouteImport } from './routes/_authenticated/library/$itemId/takeaways/new'
import { Route as AuthenticatedLibraryItemIdSectionsSectionIdRouteImport } from './routes/_authenticated/library/$itemId/sections/$sectionId'
import { Route as AuthenticatedLibraryItemIdNotesNoteIdRouteImport } from './routes/_authenticated/library/$itemId/notes/$noteId'
import { Route as AuthenticatedLibraryItemIdTakeawaysTakeawayIdIndexRouteImport } from './routes/_authenticated/library/$itemId/takeaways/$takeawayId/index'
import { Route as AuthenticatedLibraryItemIdTakeawaysTakeawayIdEditRouteImport } from './routes/_authenticated/library/$itemId/takeaways/$takeawayId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGraphRoute = AuthenticatedGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuggestionsIndexRoute =
  AuthenticatedSuggestionsIndexRouteImport.update({
    id: '/suggestions/',
    path: '/suggestions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedNotesIdRoute = AuthenticatedNotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryCollectionsIndexRoute =
  AuthenticatedLibraryCollectionsIndexRouteImport.update({
    id: '/library/collections/',
    path: '/library/collections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryItemIdIndexRoute =
  AuthenticatedLibraryItemIdIndexRouteImport.update({
    id: '/library/$itemId/',
    path: '/library/$itemId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiscoverPodcastsIndexRoute =
  AuthenticatedDiscoverPodcastsIndexRouteImport.update({
    id: '/discover/podcasts/',
    path: '/discover/podcasts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedLibraryCollectionsCollectionIdRoute =
  AuthenticatedLibraryCollectionsCollectionIdRouteImport.update({
    id: '/library/collections/$collectionId',
    path: '/library/collections/$collectionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryItemIdTranscriptRoute =
  AuthenticatedLibraryItemIdTranscriptRouteImport.update({
    id: '/library/$itemId/transcript',
    path: '/library/$itemId/transcript',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryItemIdReflectRoute =
  AuthenticatedLibraryItemIdReflectRouteImport.update({
    id: '/library/$itemId/reflect',
    path: '/library/$itemId/reflect',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryItemIdHighlightsRoute =
  AuthenticatedLibraryItemIdHighlightsRouteImport.update({
    id: '/library/$itemId/highlights',
    path: '/library/$itemId/highlights',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiscoverPodcastsSlugRoute =
  AuthenticatedDiscoverPodcastsSlugRouteImport.update({
    id: '/discover/podcasts/$slug',
    path: '/discover/podcasts/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedLibraryItemIdTakeawaysIndexRoute =
  AuthenticatedLibraryItemIdTakeawaysIndexRouteImport.update({
    id: '/library/$itemId/takeaways/',
    path: '/library/$itemId/takeaways/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryItemIdNotesIndexRoute =
  AuthenticatedLibraryItemIdNotesIndexRouteImport.update({
    id: '/library/$itemId/notes/',
    path: '/library/$itemId/notes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryItemIdTakeawaysNewRoute =
  AuthenticatedLibraryItemIdTakeawaysNewRouteImport.update({
    id: '/library/$itemId/takeaways/new',
    path: '/library/$itemId/takeaways/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryItemIdSectionsSectionIdRoute =
  AuthenticatedLibraryItemIdSectionsSectionIdRouteImport.update({
    id: '/library/$itemId/sections/$sectionId',
    path: '/library/$itemId/sections/$sectionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryItemIdNotesNoteIdRoute =
  AuthenticatedLibraryItemIdNotesNoteIdRouteImport.update({
    id: '/library/$itemId/notes/$noteId',
    path: '/library/$itemId/notes/$noteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryItemIdTakeawaysTakeawayIdIndexRoute =
  AuthenticatedLibraryItemIdTakeawaysTakeawayIdIndexRouteImport.update({
    id: '/library/$itemId/takeaways/$takeawayId/',
    path: '/library/$itemId/takeaways/$takeawayId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryItemIdTakeawaysTakeawayIdEditRoute =
  AuthenticatedLibraryItemIdTakeawaysTakeawayIdEditRouteImport.update({
    id: '/library/$itemId/takeaways/$takeawayId/edit',
    path: '/library/$itemId/takeaways/$takeawayId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/ask': typeof AuthenticatedAskRoute
  '/graph': typeof AuthenticatedGraphRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/notes/$id': typeof AuthenticatedNotesIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/notes/': typeof AuthenticatedNotesIndexRoute
  '/suggestions/': typeof AuthenticatedSuggestionsIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/discover/podcasts/$slug': typeof AuthenticatedDiscoverPodcastsSlugRoute
  '/library/$itemId/highlights': typeof AuthenticatedLibraryItemIdHighlightsRoute
  '/library/$itemId/reflect': typeof AuthenticatedLibraryItemIdReflectRoute
  '/library/$itemId/transcript': typeof AuthenticatedLibraryItemIdTranscriptRoute
  '/library/collections/$collectionId': typeof AuthenticatedLibraryCollectionsCollectionIdRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/discover/podcasts/': typeof AuthenticatedDiscoverPodcastsIndexRoute
  '/library/$itemId/': typeof AuthenticatedLibraryItemIdIndexRoute
  '/library/collections/': typeof AuthenticatedLibraryCollectionsIndexRoute
  '/library/$itemId/notes/$noteId': typeof AuthenticatedLibraryItemIdNotesNoteIdRoute
  '/library/$itemId/sections/$sectionId': typeof AuthenticatedLibraryItemIdSectionsSectionIdRoute
  '/library/$itemId/takeaways/new': typeof AuthenticatedLibraryItemIdTakeawaysNewRoute
  '/library/$itemId/notes/': typeof AuthenticatedLibraryItemIdNotesIndexRoute
  '/library/$itemId/takeaways/': typeof AuthenticatedLibraryItemIdTakeawaysIndexRoute
  '/library/$itemId/takeaways/$takeawayId/edit': typeof AuthenticatedLibraryItemIdTakeawaysTakeawayIdEditRoute
  '/library/$itemId/takeaways/$takeawayId/': typeof AuthenticatedLibraryItemIdTakeawaysTakeawayIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ask': typeof AuthenticatedAskRoute
  '/graph': typeof AuthenticatedGraphRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/notes/$id': typeof AuthenticatedNotesIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/notes': typeof AuthenticatedNotesIndexRoute
  '/suggestions': typeof AuthenticatedSuggestionsIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/discover/podcasts/$slug': typeof AuthenticatedDiscoverPodcastsSlugRoute
  '/library/$itemId/highlights': typeof AuthenticatedLibraryItemIdHighlightsRoute
  '/library/$itemId/reflect': typeof AuthenticatedLibraryItemIdReflectRoute
  '/library/$itemId/transcript': typeof AuthenticatedLibraryItemIdTranscriptRoute
  '/library/collections/$collectionId': typeof AuthenticatedLibraryCollectionsCollectionIdRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/discover/podcasts': typeof AuthenticatedDiscoverPodcastsIndexRoute
  '/library/$itemId': typeof AuthenticatedLibraryItemIdIndexRoute
  '/library/collections': typeof AuthenticatedLibraryCollectionsIndexRoute
  '/library/$itemId/notes/$noteId': typeof AuthenticatedLibraryItemIdNotesNoteIdRoute
  '/library/$itemId/sections/$sectionId': typeof AuthenticatedLibraryItemIdSectionsSectionIdRoute
  '/library/$itemId/takeaways/new': typeof AuthenticatedLibraryItemIdTakeawaysNewRoute
  '/library/$itemId/notes': typeof AuthenticatedLibraryItemIdNotesIndexRoute
  '/library/$itemId/takeaways': typeof AuthenticatedLibraryItemIdTakeawaysIndexRoute
  '/library/$itemId/takeaways/$takeawayId/edit': typeof AuthenticatedLibraryItemIdTakeawaysTakeawayIdEditRoute
  '/library/$itemId/takeaways/$takeawayId': typeof AuthenticatedLibraryItemIdTakeawaysTakeawayIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/graph': typeof AuthenticatedGraphRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/notes/$id': typeof AuthenticatedNotesIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute
  '/_authenticated/suggestions/': typeof AuthenticatedSuggestionsIndexRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/discover/podcasts/$slug': typeof AuthenticatedDiscoverPodcastsSlugRoute
  '/_authenticated/library/$itemId/highlights': typeof AuthenticatedLibraryItemIdHighlightsRoute
  '/_authenticated/library/$itemId/reflect': typeof AuthenticatedLibraryItemIdReflectRoute
  '/_authenticated/library/$itemId/transcript': typeof AuthenticatedLibraryItemIdTranscriptRoute
  '/_authenticated/library/collections/$collectionId': typeof AuthenticatedLibraryCollectionsCollectionIdRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/discover/podcasts/': typeof AuthenticatedDiscoverPodcastsIndexRoute
  '/_authenticated/library/$itemId/': typeof AuthenticatedLibraryItemIdIndexRoute
  '/_authenticated/library/collections/': typeof AuthenticatedLibraryCollectionsIndexRoute
  '/_authenticated/library/$itemId/notes/$noteId': typeof AuthenticatedLibraryItemIdNotesNoteIdRoute
  '/_authenticated/library/$itemId/sections/$sectionId': typeof AuthenticatedLibraryItemIdSectionsSectionIdRoute
  '/_authenticated/library/$itemId/takeaways/new': typeof AuthenticatedLibraryItemIdTakeawaysNewRoute
  '/_authenticated/library/$itemId/notes/': typeof AuthenticatedLibraryItemIdNotesIndexRoute
  '/_authenticated/library/$itemId/takeaways/': typeof AuthenticatedLibraryItemIdTakeawaysIndexRoute
  '/_authenticated/library/$itemId/takeaways/$takeawayId/edit': typeof AuthenticatedLibraryItemIdTakeawaysTakeawayIdEditRoute
  '/_authenticated/library/$itemId/takeaways/$takeawayId/': typeof AuthenticatedLibraryItemIdTakeawaysTakeawayIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/ask'
    | '/graph'
    | '/profile'
    | '/notes/$id'
    | '/admin/'
    | '/library/'
    | '/notes/'
    | '/suggestions/'
    | '/admin/users/$id'
    | '/discover/podcasts/$slug'
    | '/library/$itemId/highlights'
    | '/library/$itemId/reflect'
    | '/library/$itemId/transcript'
    | '/library/collections/$collectionId'
    | '/admin/users/'
    | '/discover/podcasts/'
    | '/library/$itemId/'
    | '/library/collections/'
    | '/library/$itemId/notes/$noteId'
    | '/library/$itemId/sections/$sectionId'
    | '/library/$itemId/takeaways/new'
    | '/library/$itemId/notes/'
    | '/library/$itemId/takeaways/'
    | '/library/$itemId/takeaways/$takeawayId/edit'
    | '/library/$itemId/takeaways/$takeawayId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ask'
    | '/graph'
    | '/profile'
    | '/'
    | '/notes/$id'
    | '/admin'
    | '/library'
    | '/notes'
    | '/suggestions'
    | '/admin/users/$id'
    | '/discover/podcasts/$slug'
    | '/library/$itemId/highlights'
    | '/library/$itemId/reflect'
    | '/library/$itemId/transcript'
    | '/library/collections/$collectionId'
    | '/admin/users'
    | '/discover/podcasts'
    | '/library/$itemId'
    | '/library/collections'
    | '/library/$itemId/notes/$noteId'
    | '/library/$itemId/sections/$sectionId'
    | '/library/$itemId/takeaways/new'
    | '/library/$itemId/notes'
    | '/library/$itemId/takeaways'
    | '/library/$itemId/takeaways/$takeawayId/edit'
    | '/library/$itemId/takeaways/$takeawayId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/ask'
    | '/_authenticated/graph'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/notes/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/library/'
    | '/_authenticated/notes/'
    | '/_authenticated/suggestions/'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/discover/podcasts/$slug'
    | '/_authenticated/library/$itemId/highlights'
    | '/_authenticated/library/$itemId/reflect'
    | '/_authenticated/library/$itemId/transcript'
    | '/_authenticated/library/collections/$collectionId'
    | '/_authenticated/admin/users/'
    | '/_authenticated/discover/podcasts/'
    | '/_authenticated/library/$itemId/'
    | '/_authenticated/library/collections/'
    | '/_authenticated/library/$itemId/notes/$noteId'
    | '/_authenticated/library/$itemId/sections/$sectionId'
    | '/_authenticated/library/$itemId/takeaways/new'
    | '/_authenticated/library/$itemId/notes/'
    | '/_authenticated/library/$itemId/takeaways/'
    | '/_authenticated/library/$itemId/takeaways/$takeawayId/edit'
    | '/_authenticated/library/$itemId/takeaways/$takeawayId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/graph': {
      id: '/_authenticated/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AuthenticatedGraphRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suggestions/': {
      id: '/_authenticated/suggestions/'
      path: '/suggestions'
      fullPath: '/suggestions/'
      preLoaderRoute: typeof AuthenticatedSuggestionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/notes/$id': {
      id: '/_authenticated/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof AuthenticatedNotesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/collections/': {
      id: '/_authenticated/library/collections/'
      path: '/library/collections'
      fullPath: '/library/collections/'
      preLoaderRoute: typeof AuthenticatedLibraryCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$itemId/': {
      id: '/_authenticated/library/$itemId/'
      path: '/library/$itemId'
      fullPath: '/library/$itemId/'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discover/podcasts/': {
      id: '/_authenticated/discover/podcasts/'
      path: '/discover/podcasts'
      fullPath: '/discover/podcasts/'
      preLoaderRoute: typeof AuthenticatedDiscoverPodcastsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/library/collections/$collectionId': {
      id: '/_authenticated/library/collections/$collectionId'
      path: '/library/collections/$collectionId'
      fullPath: '/library/collections/$collectionId'
      preLoaderRoute: typeof AuthenticatedLibraryCollectionsCollectionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$itemId/transcript': {
      id: '/_authenticated/library/$itemId/transcript'
      path: '/library/$itemId/transcript'
      fullPath: '/library/$itemId/transcript'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdTranscriptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$itemId/reflect': {
      id: '/_authenticated/library/$itemId/reflect'
      path: '/library/$itemId/reflect'
      fullPath: '/library/$itemId/reflect'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdReflectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$itemId/highlights': {
      id: '/_authenticated/library/$itemId/highlights'
      path: '/library/$itemId/highlights'
      fullPath: '/library/$itemId/highlights'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdHighlightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discover/podcasts/$slug': {
      id: '/_authenticated/discover/podcasts/$slug'
      path: '/discover/podcasts/$slug'
      fullPath: '/discover/podcasts/$slug'
      preLoaderRoute: typeof AuthenticatedDiscoverPodcastsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/library/$itemId/takeaways/': {
      id: '/_authenticated/library/$itemId/takeaways/'
      path: '/library/$itemId/takeaways'
      fullPath: '/library/$itemId/takeaways/'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdTakeawaysIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$itemId/notes/': {
      id: '/_authenticated/library/$itemId/notes/'
      path: '/library/$itemId/notes'
      fullPath: '/library/$itemId/notes/'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$itemId/takeaways/new': {
      id: '/_authenticated/library/$itemId/takeaways/new'
      path: '/library/$itemId/takeaways/new'
      fullPath: '/library/$itemId/takeaways/new'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdTakeawaysNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$itemId/sections/$sectionId': {
      id: '/_authenticated/library/$itemId/sections/$sectionId'
      path: '/library/$itemId/sections/$sectionId'
      fullPath: '/library/$itemId/sections/$sectionId'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdSectionsSectionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$itemId/notes/$noteId': {
      id: '/_authenticated/library/$itemId/notes/$noteId'
      path: '/library/$itemId/notes/$noteId'
      fullPath: '/library/$itemId/notes/$noteId'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$itemId/takeaways/$takeawayId/': {
      id: '/_authenticated/library/$itemId/takeaways/$takeawayId/'
      path: '/library/$itemId/takeaways/$takeawayId'
      fullPath: '/library/$itemId/takeaways/$takeawayId/'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdTakeawaysTakeawayIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$itemId/takeaways/$takeawayId/edit': {
      id: '/_authenticated/library/$itemId/takeaways/$takeawayId/edit'
      path: '/library/$itemId/takeaways/$takeawayId/edit'
      fullPath: '/library/$itemId/takeaways/$takeawayId/edit'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdTakeawaysTakeawayIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedGraphRoute: typeof AuthenticatedGraphRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedNotesIdRoute: typeof AuthenticatedNotesIdRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute
  AuthenticatedSuggestionsIndexRoute: typeof AuthenticatedSuggestionsIndexRoute
  AuthenticatedDiscoverPodcastsSlugRoute: typeof AuthenticatedDiscoverPodcastsSlugRoute
  AuthenticatedLibraryItemIdHighlightsRoute: typeof AuthenticatedLibraryItemIdHighlightsRoute
  AuthenticatedLibraryItemIdReflectRoute: typeof AuthenticatedLibraryItemIdReflectRoute
  AuthenticatedLibraryItemIdTranscriptRoute: typeof AuthenticatedLibraryItemIdTranscriptRoute
  AuthenticatedLibraryCollectionsCollectionIdRoute: typeof AuthenticatedLibraryCollectionsCollectionIdRoute
  AuthenticatedDiscoverPodcastsIndexRoute: typeof AuthenticatedDiscoverPodcastsIndexRoute
  AuthenticatedLibraryItemIdIndexRoute: typeof AuthenticatedLibraryItemIdIndexRoute
  AuthenticatedLibraryCollectionsIndexRoute: typeof AuthenticatedLibraryCollectionsIndexRoute
  AuthenticatedLibraryItemIdNotesNoteIdRoute: typeof AuthenticatedLibraryItemIdNotesNoteIdRoute
  AuthenticatedLibraryItemIdSectionsSectionIdRoute: typeof AuthenticatedLibraryItemIdSectionsSectionIdRoute
  AuthenticatedLibraryItemIdTakeawaysNewRoute: typeof AuthenticatedLibraryItemIdTakeawaysNewRoute
  AuthenticatedLibraryItemIdNotesIndexRoute: typeof AuthenticatedLibraryItemIdNotesIndexRoute
  AuthenticatedLibraryItemIdTakeawaysIndexRoute: typeof AuthenticatedLibraryItemIdTakeawaysIndexRoute
  AuthenticatedLibraryItemIdTakeawaysTakeawayIdEditRoute: typeof AuthenticatedLibraryItemIdTakeawaysTakeawayIdEditRoute
  AuthenticatedLibraryItemIdTakeawaysTakeawayIdIndexRoute: typeof AuthenticatedLibraryItemIdTakeawaysTakeawayIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedGraphRoute: AuthenticatedGraphRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedNotesIdRoute: AuthenticatedNotesIdRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
  AuthenticatedSuggestionsIndexRoute: AuthenticatedSuggestionsIndexRoute,
  AuthenticatedDiscoverPodcastsSlugRoute:
    AuthenticatedDiscoverPodcastsSlugRoute,
  AuthenticatedLibraryItemIdHighlightsRoute:
    AuthenticatedLibraryItemIdHighlightsRoute,
  AuthenticatedLibraryItemIdReflectRoute:
    AuthenticatedLibraryItemIdReflectRoute,
  AuthenticatedLibraryItemIdTranscriptRoute:
    AuthenticatedLibraryItemIdTranscriptRoute,
  AuthenticatedLibraryCollectionsCollectionIdRoute:
    AuthenticatedLibraryCollectionsCollectionIdRoute,
  AuthenticatedDiscoverPodcastsIndexRoute:
    AuthenticatedDiscoverPodcastsIndexRoute,
  AuthenticatedLibraryItemIdIndexRoute: AuthenticatedLibraryItemIdIndexRoute,
  AuthenticatedLibraryCollectionsIndexRoute:
    AuthenticatedLibraryCollectionsIndexRoute,
  AuthenticatedLibraryItemIdNotesNoteIdRoute:
    AuthenticatedLibraryItemIdNotesNoteIdRoute,
  AuthenticatedLibraryItemIdSectionsSectionIdRoute:
    AuthenticatedLibraryItemIdSectionsSectionIdRoute,
  AuthenticatedLibraryItemIdTakeawaysNewRoute:
    AuthenticatedLibraryItemIdTakeawaysNewRoute,
  AuthenticatedLibraryItemIdNotesIndexRoute:
    AuthenticatedLibraryItemIdNotesIndexRoute,
  AuthenticatedLibraryItemIdTakeawaysIndexRoute:
    AuthenticatedLibraryItemIdTakeawaysIndexRoute,
  AuthenticatedLibraryItemIdTakeawaysTakeawayIdEditRoute:
    AuthenticatedLibraryItemIdTakeawaysTakeawayIdEditRoute,
  AuthenticatedLibraryItemIdTakeawaysTakeawayIdIndexRoute:
    AuthenticatedLibraryItemIdTakeawaysTakeawayIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
